test_x<-read.table('test/X_test.txt')
test_y<-read.table('test/y_test.txt')
test_subject<-read.table('test/subject_test.txt')
test_x$label<-test_y$V1
test_x$subject<-test_subject$V1
train_x<-read.table('train/X_train.txt')
train_y<-read.table('train/y_train.txt')
train_subject<-read.table('train/subject_train.txt')
train_x$label<-train_y$V1
train_x$subject<-train_subject$V1
mergedDataset<-rbind(train_x,test_x)
activity_labels<-read.table("activity_labels.txt")
features<-read.table("features.txt")
substring_mean<-"mean()"
substring_std<-"std()"
relevant_features<-features[grepl(substring_mean,features$V2,fixed=TRUE)|grepl(substring_std,features$V2,fixed=TRUE),]
filter<-relevant_features$V1
label_subject<-c(ncol(mergedDataset)-1,ncol(mergedDataset)) #labels and subject columns
updated_filter<-c(filter,label_subject)
filteredDataset<-mergedDataset[updated_filter]
collabels<-relevant_features$V2
collabels<-as.character(collabels)
colnames(filteredDataset)[1:length(collabels)]<-collabels
mergeActivityLabel<-merge(filteredDataset,activity_labels,by.x="label",by.y="V1")
names(mergeActivityLabel)[length(mergeActivityLabel)]<-"activity"
mergeActivityLabel$label<-NULL
finalDataset<-mergeActivityLabel
grouped_data<-group_by(finalDataset,subject,activity)
result<-summarise_each(grouped_data,funs(mean))
